spring:
  application:
    name: astra-capone-poc
  data:
    cassandra:
      keyspace-name: test_ks
      contact-points:
        - 127.0.0.1:9042
      local-datacenter: dc1
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

server.port: 8080
      
datastax.astra:
    secure-connect-bundle: secure-connect.zip


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

cassandra.metrics:
  session-metrics:
    - bytes-sent
    - connected-nodes
  node-metrics:
    - pool.open-connections
    - pool.in-flight
    - speculative-executions

speculative-executions:
  retry-times: 3
  delay-millis: 2