spring:
  application:
    name: astra-capone-poc
  data:
    cassandra:
      keyspace-name: test_ks
      contact-points:
        - 127.0.0.1:9042
      local-datacenter: dc1
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

server.port: 8080
      
datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
  id: 84fb5b23-0476-4789-8eb4-59d553216d74
  region: us-east-1
  keyspace: test_ks
  application.token: AstraCS:ntRECwopxDYoFIcRKcRMdETi:f8d3d4872d7eb4059382c41b18a34ce7856cc20b97d97726bd3ccd663b090c58
  timeout: 5

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

cassandra.metrics:
  session-metrics:
    - bytes-sent
    - connected-nodes
  node-metrics:
    - pool.open-connections
    - pool.in-flight
    - speculative-executions
