spring:
  application:
    name: astra-capone-poc
  data:
    cassandra:
      keyspace-name: test_ks
      username: ntRECwopxDYoFIcRKcRMdETi
      password: CLxr0zZAQ.cWTcKQCBw7,a0B5SeCKNfyUyNZwB-C_dNdCeKtrqjQWW9MSBnnLya2XhL4ds8tHIsP7ny,0UHmLPC9NRMA91BHNyM2C36w_ucd9XeyYuwI_83mT,eDNuFi
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

server.port: 8080
      
datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
  id: 84fb5b23-0476-4789-8eb4-59d553216d74
  region: us-east-1
  keyspace: test_ks
  application.token: AstraCS:ntRECwopxDYoFIcRKcRMdETi:f8d3d4872d7eb4059382c41b18a34ce7856cc20b97d97726bd3ccd663b090c58
  timeout: 5

